 Container pedro-azevedo-e-matheus-gomes-nodejs-db-1  Creating
 Container pedro-azevedo-e-matheus-gomes-nodejs-db-1  Created
 Container pedro-azevedo-e-matheus-gomes-nodejs-api1-1  Creating
 Container pedro-azevedo-e-matheus-gomes-nodejs-api2-1  Creating
 Container pedro-azevedo-e-matheus-gomes-nodejs-api2-1  Created
 Container pedro-azevedo-e-matheus-gomes-nodejs-api1-1  Created
 Container pedro-azevedo-e-matheus-gomes-nodejs-nginx-1  Creating
 Container pedro-azevedo-e-matheus-gomes-nodejs-nginx-1  Created
Attaching to api1-1, api2-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | sh: locale: not found
db-1     | 2024-03-03 01:45:24.659 UTC [30] WARNING:  no usable system locales were found
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
api1-1   | npm ERR! code ENOENT
api1-1   | npm ERR! syscall open
api1-1   | npm ERR! path /app/package.json
api1-1   | npm ERR! errno -2
api1-1   | npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
api1-1   | npm ERR! enoent This is related to npm not being able to find a file.
api1-1   | npm ERR! enoent 
api1-1   | 
api1-1   | npm ERR! A complete log of this run can be found in:
api1-1   | npm ERR!     /root/.npm/_logs/2024-03-03T01_45_25_337Z-debug-0.log
api2-1   | npm ERR! code ENOENT
api2-1   | npm ERR! syscall open
api2-1   | npm ERR! path /app/package.json
api2-1   | npm ERR! errno -2
api2-1   | npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
api2-1   | npm ERR! enoent This is related to npm not being able to find a file.
api2-1   | npm ERR! enoent 
api2-1   | 
api2-1   | npm ERR! A complete log of this run can be found in:
api2-1   | npm ERR!     /root/.npm/_logs/2024-03-03T01_45_25_418Z-debug-0.log
api1-1 exited with code 254
api2-1 exited with code 254
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | You can change this by editing pg_hba.conf or using the option -A, or
db-1     | --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-03-03 01:45:26.274 UTC [36] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db-1     | 2024-03-03 01:45:26.277 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-03 01:45:26.286 UTC [37] LOG:  database system was shut down at 2024-03-03 01:45:25 UTC
db-1     | 2024-03-03 01:45:26.293 UTC [36] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-03-03 01:45:26.904 UTC [36] LOG:  received fast shutdown request
db-1     | .2024-03-03 01:45:26.907 UTC [36] LOG:  aborting any active transactions
db-1     | 2024-03-03 01:45:26.908 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db-1     | 2024-03-03 01:45:26.908 UTC [38] LOG:  shutting down
db-1     | 2024-03-03 01:45:27.026 UTC [36] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-03 01:45:27.123 UTC [1] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db-1     | 2024-03-03 01:45:27.123 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-03 01:45:27.123 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-03 01:45:27.128 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-03 01:45:27.134 UTC [52] LOG:  database system was shut down at 2024-03-03 01:45:27 UTC
db-1     | 2024-03-03 01:45:27.140 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/03/03 01:45:28 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:28 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:30 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:30 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:32 [error] 31#31: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:32 [error] 31#31: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:34 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:34 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:36 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:38 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:40 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:40 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:42 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:44 [error] 29#29: *19 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:46 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:48 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:50 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:52 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:52 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:54 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:56 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:45:58 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:46:00 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:46:02 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:46:04 [error] 29#29: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:46:04 [error] 29#29: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/03 01:46:06 [error] 29#29: *34 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-03-03 01:46:08.833 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-03 01:46:08.865 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-03 01:46:08.866 UTC [1] LOG:  background worker "logical replication launcher" (PID 58) exited with exit code 1
db-1     | 2024-03-03 01:46:08.866 UTC [53] LOG:  shutting down
db-1     | 2024-03-03 01:46:08.905 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
